language: python
services:
    - docker

before_script:
    # multiarch builds
    - docker --version  # document the version Travis is using (currently 17.x, which is way too old)
    - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json # try to use manifests
    - mkdir -p $HOME/.docker
    - echo '{"experimental":"enabled"}' | tee $HOME/.docker/config.json # needed to use docker manifest
    - sudo service docker restart
    - sudo docker run --rm --privileged multiarch/qemu-user-static:register --reset

    # dependencies
    - sudo pip install j2cli

    # authorization
    - echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_USERNAME" --password-stdin
    - echo "$QUAY_PASSWORD" | sudo docker login -u "$QUAY_USERNAME" --password-stdin quay.io

script:
    - make all SLACK_URL=$SLACK_URL

after_failure:
    - ./notify.sh "${SLACK_URL}" "dokuwiki containers build failure"
