language: python
if: branch = master
services:
    - docker

before_script:
    # dependencies
    - pip install j2cli requests
    - wget https://github.com/riotkit-org/ci-utils/archive/v2.0.0.zip -O /tmp/ci-utils.zip
    - curl "https://raw.githubusercontent.com/riotkit-org/ci-utils/v2.0.0/ci-integration/travis.sh" -s | bash

    # activate ARM builds on travis
    - /opt/riotkit/utils/bin/setup-travis-arm-builds

    # authorization
    - echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_USERNAME" --password-stdin
    - echo "$QUAY_PASSWORD" | sudo docker login -u "$QUAY_USERNAME" --password-stdin quay.io

after_failure:
    - ./notify.sh "${SLACK_URL}" "dokuwiki containers build failure "

jobs:
    include:
        - stage: Build stable
          script:
              - make build clean VERSION=stable

        - stage: Build old stable
          script:
              - make build clean VERSION=old-stable

        - stage: Build snapshot
          script:
              - make build clean VERSION=snapshot
