FROM {{ FROM_IMAGE }}

LABEL maintainer="RiotKit" \
  org.label-schema.name="dokuwiki" \
  org.label-schema.description="DokuWiki" \
  org.label-schema.url="https://github.com/riotkit-org" \
  org.label-schema.vcs-url="https://github.com/riotkit-org/docker-dokuwiki" \
  org.label-schema.vendor="RiotKit" \
  org.label-schema.version="{{ VERSION }}"

ENV NGINX_ENABLE_DEFAULT_LOCATION_INDEX=false \
    WWW_USER_ID=1000 \
    WWW_GROUP_ID=1000 \
    DOKUWIKI_VERSION={{ VERSION }}

ADD ./application.tar.gz /var/www/html/
COPY etc/nginx/conf.d/* /.etc.template/nginx/conf.d/
